[package]
name = "password_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql= "22.0"
base64 = "0.13.0"
aes = "0.8.0"
block-modes = "0.8.1"
block-padding = "0.2.1"
hex = "0.4.2"
rand = "0.8.5"